-- Zentrales, unveränderbares Änderungsprotokoll für das Bestellportal.
-- Die Trigger erfassen INSERT, UPDATE und DELETE direkt in der Datenbank.

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid,
  actor_name text,
  actor_email text,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  table_name text not null,
  record_id text,
  order_id uuid,
  order_number text,
  area text,
  changed_fields text[],
  old_data jsonb,
  new_data jsonb
);

create index if not exists audit_log_occurred_at_idx on public.audit_log (occurred_at desc);
create index if not exists audit_log_actor_id_idx on public.audit_log (actor_id, occurred_at desc);
create index if not exists audit_log_order_id_idx on public.audit_log (order_id, occurred_at desc);
create index if not exists audit_log_table_name_idx on public.audit_log (table_name, occurred_at desc);

alter table public.audit_log enable row level security;

drop policy if exists audit_log_select_admin on public.audit_log;
create policy audit_log_select_admin
on public.audit_log
for select
to authenticated
using (public.is_admin_user());

grant select on public.audit_log to authenticated;
revoke insert, update, delete, truncate on public.audit_log from anon, authenticated;

create or replace function public.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  previous_data jsonb;
  current_data jsonb;
  row_data jsonb;
  audit_actor_id uuid;
  audit_actor_name text;
  audit_actor_email text;
  audit_order_id uuid;
  audit_order_number text;
  audit_area text;
  audit_record_id text;
  audit_changed_fields text[];
begin
  previous_data := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  current_data := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  row_data := coalesce(current_data, previous_data, '{}'::jsonb);

  if tg_op = 'UPDATE' then
    select coalesce(array_agg(field_name order by field_name), '{}'::text[])
      into audit_changed_fields
    from (
      select fields.field_name
      from jsonb_object_keys(current_data) as fields(field_name)
      where fields.field_name <> 'updated_at'
        and previous_data -> fields.field_name is distinct from current_data -> fields.field_name
    ) changed;

    if cardinality(audit_changed_fields) = 0 then
      return new;
    end if;
  end if;

  audit_actor_id := auth.uid();
  if audit_actor_id is not null then
    select profiles.full_name, profiles.email
      into audit_actor_name, audit_actor_email
    from public.profiles
    where profiles.id = audit_actor_id;
  end if;
  audit_actor_email := coalesce(audit_actor_email, auth.jwt() ->> 'email');

  if tg_table_name = 'material_orders' then
    audit_order_id := nullif(row_data ->> 'id', '')::uuid;
    audit_order_number := row_data ->> 'order_number';
    audit_area := row_data ->> 'order_area';
  elsif tg_table_name in ('order_items', 'goods_receipts', 'scrap_items', 'order_pdfs', 'order_history') then
    audit_order_id := nullif(row_data ->> 'material_order_id', '')::uuid;
    select orders.order_number, orders.order_area
      into audit_order_number, audit_area
    from public.material_orders orders
    where orders.id = audit_order_id;
  else
    audit_area := row_data ->> 'order_area';
  end if;

  if tg_table_name = 'profiles' then
    audit_area := 'administration';
  elsif audit_area is null and tg_table_name in (
    'customers', 'suppliers', 'materials', 'material_thicknesses',
    'cross_sections', 'work_preparations', 'formats', 'packaging_defaults'
  ) then
    audit_area := 'stammdaten';
  elsif audit_area is null and tg_table_name = 'inbound_email_attachments' then
    audit_area := 'email-import';
  end if;

  audit_record_id := coalesce(
    row_data ->> 'id',
    row_data ->> 'name',
    row_data ->> 'material_order_id'
  );

  insert into public.audit_log (
    actor_id,
    actor_name,
    actor_email,
    action,
    table_name,
    record_id,
    order_id,
    order_number,
    area,
    changed_fields,
    old_data,
    new_data
  ) values (
    audit_actor_id,
    audit_actor_name,
    audit_actor_email,
    tg_op,
    tg_table_name,
    audit_record_id,
    audit_order_id,
    audit_order_number,
    audit_area,
    audit_changed_fields,
    previous_data,
    current_data
  );

  if tg_op = 'DELETE' then
    return old;
  end if;

  return new;
end;
$$;

revoke all on function public.write_audit_log() from public;

do $$
declare
  audited_table text;
begin
  foreach audited_table in array array[
    'material_orders',
    'order_items',
    'goods_receipts',
    'scrap_items',
    'order_pdfs',
    'customers',
    'suppliers',
    'materials',
    'material_thicknesses',
    'cross_sections',
    'work_preparations',
    'formats',
    'packaging_defaults',
    'profiles',
    'inbound_email_attachments'
  ] loop
    if to_regclass('public.' || audited_table) is not null then
      execute format('drop trigger if exists audit_changes on public.%I', audited_table);
      execute format(
        'create trigger audit_changes after insert or update or delete on public.%I for each row execute function public.write_audit_log()',
        audited_table
      );
    end if;
  end loop;
end;
$$;
